<a href="https://colab.research.google.com/github/pritam-dante/machineLearning/blob/main/numpyTutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NumPy - Numerical Python

In [1]:
import numpy as np

List vs Numpy -Time Taken

In [2]:
from time import process_time

Time taken by a list

In [3]:
python_list = [i for i in range(10000)]
start_time = process_time()
python_list = [i+5 for i in python_list]
end_time = process_time()
print(end_time - start_time)

0.0010204289999999894


In [4]:
np_array = np.array([i for i in range(10000)])
start_time = process_time()
np_array += 5
end_time = process_time()
print(end_time-start_time)

0.0010870669999993865


Numpy Arrays

In [5]:
#list
list1 = [1,2,3,4,5]
print(list1)
type(list1)

[1, 2, 3, 4, 5]


list

In [7]:
np_array = np.array([1,2,3,4,5])
print(np_array)
type(np_array)

[1 2 3 4 5]


numpy.ndarray

no commas in numpy array...and also the type is ndarray which is n-dimensional array

**Creating a 1 dimension array**

In [9]:
a = np.array([1,2,3,4,5])
print(a)
a.shape

[1 2 3 4 5]


(5,)

In [10]:
b = np.array([(1,2,3,4,5),(6,7,8,9,10)])
print(b)
b.shape

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


(2, 5)

2 rows and 5 columns

In [11]:
c = np.array([(1,2,3,4),(5,6,7,8)],dtype=float)
print(c)


[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]


**Initial Placeholder in numpy arrays**

In [12]:
#creating a numpy arrays of Zeros
x = np.zeros(5)
y = np.zeros((4,5))
print(x)
print(y)

[0. 0. 0. 0. 0.]
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
#create a numpy arrays of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
#arrays of a particular value
z = np.full((5,4),69)
print(z)

[[69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]
 [69 69 69 69]]


In [17]:
a= np.full((10),16)
print(a)

[16 16 16 16 16 16 16 16 16 16]


In [18]:
#create identity matrix
a = np.eye(5)
print(a)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [19]:
#creating a numpy array with random values
b = np.random.random((3,4)) 
print(b)

[[0.70334726 0.10039648 0.484145   0.52390999]
 [0.52757002 0.16647475 0.63859266 0.16651206]
 [0.55289374 0.94547351 0.52912514 0.27710226]]


In [20]:
#random integer values within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[92 96 74 30 24]
 [18 39 94 88 43]
 [10 67 86 66 41]]


In [25]:
#array of evenly spaced values -->specifying the number of values required
d = np.linspace(10,30,num=5)
print(d)

[10. 15. 20. 25. 30.]


In [32]:
#array of evenly spaced values --> specifying the step
e = np.arange(3)
print(e)
f = np.arange(3.0)
print(f)
g = np.arange(10,30)
print(g)
h = np.arange(10,30,5)
print(h)

[0 1 2]
[0. 1. 2.]
[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]
[10 15 20 25]


In [33]:
#convert a list to a numpy array
list2 = [1,2,3,4,5,6,7]

np_array = np.asarray(list2)
print(np_array)
type(np_array)

[1 2 3 4 5 6 7]


numpy.ndarray

**Analysing a numpy array**

In [34]:
c = np.random.randint(10,90,(5,5))
print(c)

[[43 33 62 25 38]
 [13 50 13 69 82]
 [39 65 23 63 63]
 [65 71 26 25 47]
 [30 20 15 84 58]]


In [35]:
#array dimension
print(c.shape)

(5, 5)


In [36]:
#number of dimension
print(c.ndim)

2


In [37]:
#checking the data type of the values in the array
print(c.dtype)

int64


**Mathematical operations on a np array**

In [39]:
list1 = [1,2,3,4]
list2 = [5,6,7,8]

print(list1 + list2) 
#concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8]


In [41]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

print(a)
print(b)


[[2 2 8]
 [7 8 8]
 [6 2 2]]
[[14 16 15]
 [17 12 10]
 [19 16 11]]


In [42]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[16 18 23]
 [24 20 18]
 [25 18 13]]
[[-12 -14  -7]
 [-10  -4  -2]
 [-13 -14  -9]]
[[ 28  32 120]
 [119  96  80]
 [114  32  22]]
[[0.14285714 0.125      0.53333333]
 [0.41176471 0.66666667 0.8       ]
 [0.31578947 0.125      0.18181818]]


In [43]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))

In [44]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[19 14 15]
 [14 14 17]
 [23 21 20]]
[[ -9  -6  -9]
 [-10  -8  -7]
 [-13  -3 -12]]
[[ 70  40  36]
 [ 24  33  60]
 [ 90 108  64]]
[[0.35714286 0.4        0.25      ]
 [0.16666667 0.27272727 0.41666667]
 [0.27777778 0.75       0.25      ]]


**Array Manipulation**

In [45]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[0 3 8]
 [6 6 4]]
(2, 3)


In [46]:
#transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[0 6]
 [3 6]
 [8 4]]
(3, 2)


In [48]:
#transpose2
trans2 = trans.T
print(trans2)
print(trans2.shape)

[[0 3 8]
 [6 6 4]]
(2, 3)


In [49]:
#reshaping a array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

[[1 0 5]
 [9 9 4]]
(2, 3)


In [50]:
b = a.reshape(3,2)
print(b)
print(b.shape)

[[1 0]
 [5 9]
 [9 4]]
(3, 2)


**Convert 1D array into 2D array**

In [51]:
a = np.array([1,2,3,4,5])
a.shape

(5,)

In [52]:
a2 = a[np.newaxis, :]
a2.shape

(1, 5)

In [53]:
a3 = a[:,np.newaxis]
a3.shape

(5, 1)

**Indexing and slicing**
We can index and slice NumPy arrays in the same way we can slice python lists

In [54]:
my_list = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
#          0, 1, 2, 3, 4, 5, 6, 7, 8, 9  posiive index
#        -10,-9,-8,-7,-6,-5,-4,-3,-2,-1  negative index

# list[start:stop:step] #stop is exclusive

In [59]:
print(my_list[::-1])

[9, 8, 7, 6, 5, 4, 3, 2, 1, 0]


**Reverse an array**

In [60]:
#np.flip
arr = np.array([1,2,3,4,5])
rev_arr = np.flip(arr)
print(rev_arr)


[5 4 3 2 1]
