# its better to use simpleImputer class with add_indicator attribute

In [1]:
import numpy as np
import pandas as pd

In [2]:
from sklearn.model_selection import train_test_split
from sklearn.impute import SimpleImputer,MissingIndicator

In [3]:
df = pd.read_csv('train.csv',usecols=['Age','Fare','Survived'])

In [4]:
df.sample(5)

Survived   Age   Fare
260         0   NaN   7.75
139         0  24.0  79.20
462         0  47.0  38.50
684         0  60.0  39.00
178         0  30.0  13.00

In [5]:
X = df.drop(columns=['Survived'])
y = df['Survived']

In [6]:
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
X_train.shape , X_test.shape

((712, 2), (179, 2))

In [8]:
si = SimpleImputer()
X_train_trf = si.fit_transform(X_train)
X_test_trf = si.transform(X_test)

In [11]:
X_train_trf

array([[55.5       ,  8.05      ],
       [47.        , 52.        ],
       [30.09700176, 14.5       ],
       ...,
       [30.        ,  8.05      ],
       [42.        , 26.        ],
       [18.        , 23.        ]])

In [12]:
from sklearn.linear_model import LogisticRegression

clf = LogisticRegression()

clf.fit(X_train_trf,y_train)

y_pred = clf.predict(X_test_trf)


In [13]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred)

0.6368715083798883

### using missing indicator class

In [14]:
mi = MissingIndicator()

In [15]:
mi.fit(X_train)

MissingIndicator()

In [16]:
mi.features_

array([0])

In [17]:
X_train_missing = mi.transform(X_train)

In [18]:
X_train_missing

array([[False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [ True],
       [False],
       [False],
       [ True],
       [ True],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [False],
       [

In [19]:
X_test_missing = mi.transform(X_test)

In [20]:
X_train['Age_NA'] = X_train_missing

/tmp/ipykernel_46445/2092475004.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_train['Age_NA'] = X_train_missing


In [21]:
X_train

Age     Fare  Age_NA
152  55.5   8.0500   False
110  47.0  52.0000   False
760   NaN  14.5000    True
50    7.0  39.6875   False
801  31.0  26.2500   False
..    ...      ...     ...
198   NaN   7.7500    True
44   19.0   7.8792   False
488  30.0   8.0500   False
432  42.0  26.0000   False
651  18.0  23.0000   False

[712 rows x 3 columns]

In [22]:
X_test['Age_NA'] = X_test_missing

/tmp/ipykernel_46445/1270521415.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  X_test['Age_NA'] = X_test_missing


In [23]:
si2 = SimpleImputer()

In [24]:
X_train_trf2 = si.fit_transform(X_train)
X_test_trf2 = si.transform(X_test)

In [25]:
from sklearn.linear_model import LogisticRegression
clf = LogisticRegression()

clf.fit(X_train_trf2,y_train)
y_pred2 = clf.predict(X_test_trf2)

from sklearn.metrics import accuracy_score
accuracy_score(y_test,y_pred2)

0.6480446927374302

### add 1% in the accuracy

## easy and better practice is using simple imputer only
# here it goes

In [26]:
si_final = SimpleImputer(add_indicator=True)

In [27]:
X_train_final = si_final.fit_transform(X_train)
X_test_final = si_final.transform(X_test)

In [28]:
clf_final = LogisticRegression()
clf_final.fit(X_train_final,y_train)
y_pred_final = clf_final.predict(X_test_final)
accuracy_score(y_test,y_pred_final)

0.6480446927374302